import { Navbar } from "./components/NavBar";
import ThemeRegistry from "./components/ThemeRegistry/ThemeRegistry";
import "./globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Mapa Rota - Sistema de rastreabilidade de veículos",
  description: "Generated by create next app",
  authors: [
    {
      name: "Leonardo Nascimento Cintra",
      url: "https://twitter.com/leonardoncintra",
    },
  ],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-br">
      <body>
        <ThemeRegistry>
          <Navbar />
          {children}
        </ThemeRegistry>
      </body>
    </html>
  );
}
