import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Mapa Rota",
  description: "Generated by create next app",
  authors: [{
    name: "Leonardo Nascimento Cintra",
    url: "https://twitter.com/leonardoncintra"
  }]
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-br">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
