GET http://localhost:3000/

###
GET http://localhost:3000/routes

###
GET http://localhost:3000/routes/1

### 
POST http://localhost:3000/routes
Content-Type: application/json

{
  "name": "Ronaldo Teste 1",
  "source_id": "1",  
  "destination_id": "2"
}

### Coisas do mapa

### Pegar o place_id
GET http://localhost:3000/places?text=rua jose patrocinio franca 2401

### Pegar direções entre 2 pontos
GET http://localhost:3000/directions?originId=ChIJXR0wAQrIsJQRdSxVlZd6B7Y&destinationId=ChIJg4zjaW2msJQRSX6Hcn5BG70
