GET http://localhost:3000/
npm i -g create-next-app
###
GET http://localhost:3000/routes

###
GET http://localhost:3000/routes/64e4dff8224ab4a235ea0a4a

### 
POST http://localhost:3000/routes
Content-Type: application/json

{
  "name": "Teste Kafka 5",
  "source_id": "ChIJg2nva4CnsJQRS9kSDOlAvVM",  
  "destination_id": "ChIJg4zjaW2msJQRSX6Hcn5BG70"
  
}

### Coisas do mapa

### Pegar o place_id
GET http://localhost:3000/places?text=rua seis de abril, ibiraci, mg

### Pegar direções entre 2 pontos
GET http://localhost:3000/directions?originId=ChIJXR0wAQrIsJQRdSxVlZd6B7Y&destinationId=ChIJg4zjaW2msJQRSX6Hcn5BG70
